theme = "onedark-glass"

[editor]
scrolloff = 1
scroll-lines = 2
shell = ["bash", "-c"]
auto-format = false
# idle-timeout = 1000
color-modes = true
bufferline = "always"
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-signature-help-docs = false
snippets = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
"A-]" = [":bc"]
"ret" = [":w"]
"minus" = ["goto_previous_buffer"]
"=" = ["goto_next_buffer"]
"C-f" = [":format"]
"C-r" = [":reload"]
"C-d" = ["toggle_inlay_diagnostics"]

[keys.insert]
"A-p" = ["signature_help"]
"C-d" = ["toggle_inlay_diagnostics"]

[keys.select]
"C-d" = ["toggle_inlay_diagnostics"]
